난수 상수 생성 함수 : 정규분포난수, 균등분포난수
 - tf.Variable(난수,상수) -> 변수 값 수정

In [1]:

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()


Instructions for updating:
non-resource variables are not supported in the long term


In [2]:

# 난수
num = tf.constant(10.0)

# 0차원(scala) 변수
var = tf.Variable(num+20.0) # 상수 + 상수 = scala
print("var=",var) # shape=()

# tf.random_normal 
# 1차원 변수
var1d = tf.Variable(tf.random_normal([3]))
print("var1d=",var1d) # shape=(3,) -> 3개

# tf.random_uniform : 0-1 사이의 random한 값
# 2차원 변수
var2d = tf.Variable(tf.random_uniform([3,2]))
print("var2d=",var2d) # shape=(3, 2) -> 6개

# 3차원 변수
var3d = tf.Variable(tf.random_normal([3,2,4])) # (면, 행, 열)
print("var3d=",var3d) # shape=(3, 2, 4)



var= <tf.Variable 'Variable:0' shape=() dtype=float32_ref>
var1d= <tf.Variable 'Variable_1:0' shape=(3,) dtype=float32_ref>
var2d= <tf.Variable 'Variable_2:0' shape=(3, 2) dtype=float32_ref>
var3d= <tf.Variable 'Variable_3:0' shape=(3, 2, 4) dtype=float32_ref>


In [3]:
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init) # 변수 초기화(초기값 할당) : var, var1d, var2d
    
    print("var=",sess.run(var))
    print("var1d=",sess.run(var1d))
    print("var2d=",sess.run(var2d))
    print("var3d=",sess.run(var3d))
    
    # 변수의 값 수정
    var1d_data = [0.1,0.2,0.3]
    print("var1d_add=",sess.run(var1d.assign_add(var1d_data)))
    print("수정된 var1d=",sess.run(var1d.assign(var1d_data)))
    
    var3d_re = sess.run(var3d)
    var3d_re[0] # 첫번째 면
    var3d_re[0,0] # 첫번째 면의 첫번째 행
    print(var3d_re[0].sum()) # -4.362883
    print(var3d_re[0,0].mean()) # -1.2393973


var= 30.0
var1d= [-0.23577464  1.2418805  -2.7572126 ]
var2d= [[0.11111665 0.8793129 ]
 [0.25305104 0.99877036]
 [0.54748285 0.11216998]]
var3d= [[[ 2.1593277  -1.039132    1.1667567  -0.35626736]
  [ 2.1310298   0.4663425  -1.4239552   0.25801295]]

 [[-0.33624193 -1.1410277  -0.4356664   0.28739378]
  [-0.6554656  -0.6428119   1.6367291  -1.1068252 ]]

 [[ 0.63528126 -0.8161369   1.0678734   0.7525923 ]
  [ 0.5714586   0.1277468   0.44402865  0.03549178]]]
var1d_add= [-0.13577464  1.4418806  -2.4572127 ]
수정된 var1d= [0.1 0.2 0.3]
3.3621154
0.4826713
