# 1. reshape
 - tensor의 모양변경

In [1]:
import tensorflow as tf
import numpy as np

In [7]:
print("numpy")
a = np.zeros([2,3])
print("a.shape = 2x3 \n",a)
print("a.shape = 1x6 \n",a.reshape([1,6]))
# [[0. 0. 0. 0. 0. 0.]]


print("\ntensorflow")
t = tf.zeros([2,3])
print(t)
print("\n")
print(tf.reshape(t, [1,6])) # 2 -> 1
print("\n")
print(tf.reshape(t, [3,2])) # 2 -> 2
print("\n")
print(tf.reshape(t, [2,1,3])) # 2 -> 3


numpy
a.shape = 2x3 
 [[0. 0. 0.]
 [0. 0. 0.]]
a.shape = 1x6 
 [[0. 0. 0. 0. 0. 0.]]

tensorflow
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


tf.Tensor([[0. 0. 0. 0. 0. 0.]], shape=(1, 6), dtype=float32)


tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


tf.Tensor(
[[[0. 0. 0.]]

 [[0. 0. 0.]]], shape=(2, 1, 3), dtype=float32)


# 2. squeeze
 - 1차원인 경우 제거

In [12]:
a = np.zeros( (1,2) ) # 2차:행/열
print("2차원",a)
print("1차원",np.squeeze(a)) # 1개 차원 삭제
np.squeeze(a).shape # (2,)
a.shape # (1,2)

print("\n")
b = np.zeros( (1,2,1) ) # 3차:면/행/열
print("3차원",b)
print("1차원",np.squeeze(b)) # 2개 차원 삭제
print(np.squeeze(b).shape)

print("\n")
c = np.zeros( (1,2,1,3) ) # 4차원 
print("4차원",c)
print("2차원",np.squeeze(c)) # 2개 차원 삭제 



print("\ntensorflow")
t = tf.zeros( (1,2,1,3) )
print(t.shape)

print(tf.squeeze(t)) # shape=(2, 3)

print(tf.squeeze(t).shape) # (2, 3)


2차원 [[0. 0.]]
1차원 [0. 0.]


3차원 [[[0.]
  [0.]]]
1차원 [0. 0.]
(2,)


4차원 [[[[0. 0. 0.]]

  [[0. 0. 0.]]]]
2차원 [[0. 0. 0.]
 [0. 0. 0.]]

tensorflow
(1, 2, 1, 3)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
(2, 3)


# 3. slice
 - tensor를 slice하여 새로운 tensor 생성
 
 - slice(input_, begin, size, name=None)
   - input_ : tensor
   - begin : sllice 위치(0 base)
   - size : slice 크기(1 base)

In [14]:
# 1차원 : [10] -> a = [1,2,3,4,5,6,8,9,10]
print('arr1d slice')
arr1d = tf.constant([1,2,3,4,5,6,7,8,9,10])

print(tf.slice(arr1d, [2], [4])) # [2]위치~[4]사이즈 -> [3 4 5 6]
print(tf.slice(arr1d, [3], [5])) # [4 5 6 7 8]
print(tf.slice(arr1d, [6], [-1])) # [-1]나머지 전체 -> [ 7  8  9 10]

arr1d slice
tf.Tensor([3 4 5 6], shape=(4,), dtype=int32)
tf.Tensor([4 5 6 7 8], shape=(5,), dtype=int32)
tf.Tensor([ 7  8  9 10], shape=(4,), dtype=int32)


In [15]:

# 2차원 : [2,5] -> b = [[1,2,3,4,5],[6,7,8,9,10]]
arr2d = tf.constant([[1,2,3,4,5],[6,7,8,9,10]])

print('arr2d slice')
print(tf.slice(arr2d, [0,0], [2,5])) # [0,0]:1행1열-> [2,5] slice 
print(tf.slice(arr2d, [0,0], [-1,-1])) # [0,0]:1행1열-> [2,5] slice 
print(tf.slice(arr2d, [0,2], [2,3])) # [0,2]:1행3열 -> 2행에서 3개씩 slice 



arr2d slice
tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(2, 5), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(2, 5), dtype=int32)
tf.Tensor(
[[ 3  4  5]
 [ 8  9 10]], shape=(2, 3), dtype=int32)


In [16]:
# 3차원 : [3,2,3]
print('arr3d slice')
arr3d = tf.constant([[[1, 1, 1], [2, 2, 2]],
                     [[3, 3, 3], [4, 4, 4]],
                     [[5, 5, 5], [6, 6, 6]]])

print(tf.slice(arr3d, [0,0,0], [3,2,3])) # 3차원 전체 원소 슬라이스
print(tf.slice(arr3d, [0,0,0], [1,1,1])) # [[[1]]] : 3차원 전체에서 첫번째 원소 
print(tf.slice(arr3d, [1,0,0], [1,1,2])) # [[[3 3]]] : 2면에서 2개 원소 
print(tf.slice(arr3d, [1,0,0], [1,1,3])) # [[[3 3 3]]] : 2면에서 3개 원소


arr3d slice
tf.Tensor(
[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]

 [[5 5 5]
  [6 6 6]]], shape=(3, 2, 3), dtype=int32)
tf.Tensor([[[1]]], shape=(1, 1, 1), dtype=int32)
tf.Tensor([[[3 3]]], shape=(1, 1, 2), dtype=int32)
tf.Tensor([[[3 3 3]]], shape=(1, 1, 3), dtype=int32)


In [17]:

# 문1) 2면 전체 : [[3,3,3],[4,4,4]]
print(tf.slice(arr3d,[1,0,0],[1,-1,-1]))

# 문2) 3면 2행 전체 : [[[6,6,6]]]
print(tf.slice(arr3d,[2,1,0], [1,1,-1]))


tf.Tensor(
[[[3 3 3]
  [4 4 4]]], shape=(1, 2, 3), dtype=int32)
tf.Tensor([[[6 6 6]]], shape=(1, 1, 3), dtype=int32)


# 4. expand
 - tensor에 축 단위로 차원을 추가하는 함수

In [18]:
const = tf.constant([1,2,3,4,5]) # 1차원 

print(const)
print(const.shape) # (5,)

d0 = tf.expand_dims(const, axis=0) # 행 축 2차원 
print(tf.shape(d0)) # [1 5]
print(d0) # [[1 2 3 4 5]], shape=(1, 5)
    
d1 = tf.expand_dims(const, axis=1) # 열 축 2차원 
print(tf.shape(d1)) # [5 1]
print(d1)
'''
[[1]
 [2]
 [3]
 [4]
 [5]], shape=(5, 1)
'''
    
# 행렬곱에서 차수 불일치 문제 해결
x_data = tf.constant([10,20])
x_data.shape # [2]

x_data_dim = tf.extend(x_data, axis=0)
x_data_dim.shape # [1,2]
x_data_dim # [[10,20]]

y_data = tf.constant([[1,2,3],[4,5,6]])
y_data.shape # [2,3]

mat = tf.matmul(x_data_dim,y_data)
mat # [[90,12,150]]



tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
(5,)
tf.Tensor([1 5], shape=(2,), dtype=int32)
tf.Tensor([[1 2 3 4 5]], shape=(1, 5), dtype=int32)
tf.Tensor([5 1], shape=(2,), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]
 [4]
 [5]], shape=(5, 1), dtype=int32)


AttributeError: module 'tensorflow' has no attribute 'extend'